name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19.9.0

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run docs

      - name: Generate TypeDocs
        run: npm run docs

      - name: Deploy TypeDocs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./docs
