name: Run Jest Tests on Node.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Apache Pulsar
        uses: reugn/github-action-pulsar@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.9.0' # Use your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test

      - name: Upload npm debug log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-log
          path: /home/runner/.npm/_logs/*-debug.log

      - name: Generate TypeDocs
        run: npm run docs

      - name: Show partial GH_PAT
        run: |
          echo "GH_PAT prefix: ${GH_PAT:0:8}..."
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Deploy TypeDocs
        uses: peaceiris/actions-gh-pages@v3.9.3 
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./docs
