name: Run Jest Tests on Node.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true  # Enable debug logging globally for this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Apache Pulsar
        uses: reugn/github-action-pulsar@v1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '19.9.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test

      - name: Upload npm debug log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-log
          path: /home/runner/.npm/_logs/*-debug.log
          if-no-files-found: warn

      - name: Generate TypeDocs
        run: npm run docs

      - name: Deploy TypeDocs
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
